Models/WuzzyBear.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WuzzyBears.Models
{
    public class WuzzyBear
    {
        public int Id { get; set; }


        [StringLength(15, MinimumLength = 5)]
        [Required]
        [Display(Name = "Teddy's serial Number")]
        public string TeddySerialNumber { get; set; }


        [Display(Name = "Type Of Teddy Bear")]
        [StringLength(50, MinimumLength = 5)]
        [Required]
        public string TypeOfTeddy { get; set; }


        [Display(Name = "Material Of Teddy")]
        [RegularExpression(@"^[A-Z]+[a-zA-Z\s]*$")]
        [Required]
        [StringLength(50)]
        public string MaterialOfTeddy { get; set; }


        [DataType(DataType.Date)]
        public DateTime Manufactured { get; set; }


        [Display(Name = "Size Of Teddy Bear in 'cms'")]
        public int SizeOfTeddy { get; set; }


        [Display(Name = "Cost Of Teddy Bear")]
        [Range(1, 50)]
        [DataType(DataType.Currency)]
       // [CurrencyDisplay("en-us")]
        [Column(TypeName = "decimal(18, 2)")]
        public decimal CostOfTeddy { get; set; }


        [Range(1, 5)]
        [Required]
        public int CustomerRating { get; set; }
    }
}

Controllers/WuzzyBearsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WuzzyBears.Data;
using WuzzyBears.Models;

namespace WuzzyBears.Controllers
{
    public class WuzzyBearsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public WuzzyBearsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: WuzzyBears
        /*public async Task<IActionResult> Index(string searchString)
        {
            //return View(await _context.WuzzyBear.ToListAsync());
            var Bears = from m in _context.WuzzyBear
                         select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                Bears = Bears.Where(s => s.TypeOfTeddy.Contains(searchString));
            }

            return View(await Bears.ToListAsync());
        }*/

        // GET: WuzzyBears
        public async Task<IActionResult> Index(string TeddyMaterial, string searchString)
        {
            // Use LINQ to get list of genres.
            IQueryable<string> materialQuery = from m in _context.WuzzyBear
                                            orderby m.MaterialOfTeddy
                                            select m.MaterialOfTeddy;

            var TeddyBears = from m in _context.WuzzyBear
                         select m;

            if (!string.IsNullOrEmpty(searchString))
            {
                TeddyBears = TeddyBears.Where(s => s.MaterialOfTeddy.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(TeddyMaterial))
            {
                TeddyBears = TeddyBears.Where(x => x.MaterialOfTeddy == TeddyMaterial);
            }

            var wuzzyBearMaterialVM = new WuzzyBearMaterialViewModel
            {
                Materials = new SelectList(await materialQuery.Distinct().ToListAsync()),
                WuzzyBears = await TeddyBears.ToListAsync()
            };

            return View(wuzzyBearMaterialVM);
        }

        [HttpPost]
        public string Index(string searchString, bool notUsed)
        {
            return "From [HttpPost]Index: filter on " + searchString;
        }

        // GET: WuzzyBears/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var wuzzyBear = await _context.WuzzyBear
                .FirstOrDefaultAsync(m => m.Id == id);
            if (wuzzyBear == null)
            {
                return NotFound();
            }

            return View(wuzzyBear);
        }

        // GET: WuzzyBears/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: WuzzyBears/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TeddySerialNumber,TypeOfTeddy,MaterialOfTeddy,Manufactured,SizeOfTeddy,CostOfTeddy,CustomerRating")] WuzzyBear wuzzyBear)
        {
            if (ModelState.IsValid)
            {
                _context.Add(wuzzyBear);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(wuzzyBear);
        }

        // GET: WuzzyBears/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var wuzzyBear = await _context.WuzzyBear.FindAsync(id);
            if (wuzzyBear == null)
            {
                return NotFound();
            }
            return View(wuzzyBear);
        }

        // POST: WuzzyBears/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TeddySerialNumber,TypeOfTeddy,MaterialOfTeddy,Manufactured,SizeOfTeddy,CostOfTeddy,CustomerRating")] WuzzyBear wuzzyBear)
        {
            if (id != wuzzyBear.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(wuzzyBear);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WuzzyBearExists(wuzzyBear.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(wuzzyBear);
        }

        // GET: WuzzyBears/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var wuzzyBear = await _context.WuzzyBear
                .FirstOrDefaultAsync(m => m.Id == id);
            if (wuzzyBear == null)
            {
                return NotFound();
            }

            return View(wuzzyBear);
        }

        // POST: WuzzyBears/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var wuzzyBear = await _context.WuzzyBear.FindAsync(id);
            _context.WuzzyBear.Remove(wuzzyBear);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WuzzyBearExists(int id)
        {
            return _context.WuzzyBear.Any(e => e.Id == id);
        }
    }
}

Views/WuzzyBears/Create.cshtml
@model WuzzyBears.Models.WuzzyBear

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>WuzzyBear</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TeddySerialNumber" class="control-label"></label>
                <input asp-for="TeddySerialNumber" class="form-control" />
                <span asp-validation-for="TeddySerialNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypeOfTeddy" class="control-label"></label>
                <input asp-for="TypeOfTeddy" class="form-control" />
                <span asp-validation-for="TypeOfTeddy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaterialOfTeddy" class="control-label"></label>
                <input asp-for="MaterialOfTeddy" class="form-control" />
                <span asp-validation-for="MaterialOfTeddy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Manufactured" class="control-label"></label>
                <input asp-for="Manufactured" class="form-control" />
                <span asp-validation-for="Manufactured" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SizeOfTeddy" class="control-label"></label>
                <input asp-for="SizeOfTeddy" class="form-control" />
                <span asp-validation-for="SizeOfTeddy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CostOfTeddy" class="control-label"></label>
                <input asp-for="CostOfTeddy" class="form-control" />
                <span asp-validation-for="CostOfTeddy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerRating" class="control-label"></label>
                <input asp-for="CustomerRating" class="form-control" />
                <span asp-validation-for="CustomerRating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/WuzzyBears/Delete.cshtml
@model WuzzyBears.Models.WuzzyBear

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>WuzzyBear</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TeddySerialNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TeddySerialNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TypeOfTeddy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TypeOfTeddy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaterialOfTeddy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaterialOfTeddy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Manufactured)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Manufactured)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SizeOfTeddy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SizeOfTeddy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CostOfTeddy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CostOfTeddy)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/WuzzyBears/Details.cshtml
@model WuzzyBears.Models.WuzzyBear

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>WuzzyBear</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TeddySerialNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TeddySerialNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TypeOfTeddy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TypeOfTeddy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaterialOfTeddy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaterialOfTeddy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Manufactured)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Manufactured)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SizeOfTeddy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SizeOfTeddy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CostOfTeddy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CostOfTeddy)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/WuzzyBears/Edit.cshtml
@model WuzzyBears.Models.WuzzyBear

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>WuzzyBear</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="TeddySerialNumber" class="control-label"></label>
                <input asp-for="TeddySerialNumber" class="form-control" />
                <span asp-validation-for="TeddySerialNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypeOfTeddy" class="control-label"></label>
                <input asp-for="TypeOfTeddy" class="form-control" />
                <span asp-validation-for="TypeOfTeddy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaterialOfTeddy" class="control-label"></label>
                <input asp-for="MaterialOfTeddy" class="form-control" />
                <span asp-validation-for="MaterialOfTeddy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Manufactured" class="control-label"></label>
                <input asp-for="Manufactured" class="form-control" />
                <span asp-validation-for="Manufactured" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SizeOfTeddy" class="control-label"></label>
                <input asp-for="SizeOfTeddy" class="form-control" />
                <span asp-validation-for="SizeOfTeddy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CostOfTeddy" class="control-label"></label>
                <input asp-for="CostOfTeddy" class="form-control" />
                <span asp-validation-for="CostOfTeddy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/WuzzyBears/Index.cshtml
@model WuzzyBears.Models.WuzzyBearMaterialViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="WuzzyBears" asp-action="Index" method="get">
    <p>
        <select asp-for="TeddyMaterial" asp-items="Model.Materials">
            <option value="">All</option>
        </select>
        Teddy Bear Type: <input type="text" asp-for="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.WuzzyBears[0].TeddySerialNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WuzzyBears[0].TypeOfTeddy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WuzzyBears[0].MaterialOfTeddy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WuzzyBears[0].Manufactured)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WuzzyBears[0].SizeOfTeddy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WuzzyBears[0].CostOfTeddy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WuzzyBears[0].CustomerRating)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.WuzzyBears)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TeddySerialNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TypeOfTeddy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaterialOfTeddy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Manufactured)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SizeOfTeddy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CostOfTeddy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerRating)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>